from pathlib import Path
import os
import sys
from typing import Literal

from pydantic import Field, SecretStr, field_validator, model_validator
from urllib.parse import urlsplit
from pydantic_settings import BaseSettings, SettingsConfigDict


PROJECT_ROOT = Path(getattr(sys, "_MEIPASS", Path(__file__).resolve().parents[2]))
DEFAULT_DATA_DIR = (Path(os.environ.get("LOCALAPPDATA", Path.home())) / "ApplicationTracker") if getattr(sys, "frozen", False) else PROJECT_ROOT / "data"


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=PROJECT_ROOT / ".env", env_file_encoding="utf-8", extra="ignore"
    )

    app_host: str = "127.0.0.1"
    app_port: int = Field(default=8000, ge=1, le=65535)
    app_env: str = "development"
    app_allow_remote_human: bool = False
    app_mode: Literal["local", "hosted"] = "local"
    app_public_url: str | None = None
    app_password_hash: SecretStr | None = None
    app_password_hash_file: Path | None = None
    app_session_hours: int = Field(default=8, ge=1, le=168)
    app_trusted_proxy_ips: str = "127.0.0.1"
    app_push_vapid_key_file: Path | None = None
    app_push_contact: str | None = None
    followup_delay_days: int = Field(default=7, ge=0, le=3650)
    max_followup_suggestions: int = Field(default=2, ge=0, le=100)
    app_data_dir: Path = DEFAULT_DATA_DIR
    app_static_dir: Path = PROJECT_ROOT / "frontend" / "dist"
    # MCP defaults to local stdio. Streamable HTTP stays loopback unless explicitly reconfigured.
    mcp_transport: Literal["stdio", "streamable-http"] = "stdio"
    mcp_host: str = "127.0.0.1"
    mcp_port: int = Field(default=8001, ge=1, le=65535)
    posting_check_interval_hours: int = Field(default=24, ge=1, le=8760)
    posting_check_concurrency: int = Field(default=5, ge=1, le=20)
    posting_playwright_fallback: bool = True
    log_level: Literal["critical", "error", "warning", "info", "debug", "trace"] = "info"

    @model_validator(mode="after")
    def validate_hosted_access(self):
        if self.app_push_vapid_key_file or self.app_push_contact:
            if not self.app_push_vapid_key_file or not self.app_push_contact:
                raise ValueError("Web Push requires both APP_PUSH_VAPID_KEY_FILE and APP_PUSH_CONTACT")
            if self.app_mode != "hosted" or not (self.app_public_url or "").startswith("https://"):
                raise ValueError("Web Push requires an HTTPS hosted workspace")
            from app.push_keys import read_key, validate_contact
            read_key(self.app_push_vapid_key_file)
            validate_contact(self.app_push_contact)
        if self.app_mode == "local":
            if self.app_allow_remote_human:
                raise ValueError("Remote human access requires APP_MODE=hosted with a public URL and password hash")
            return self
        parsed = urlsplit(self.app_public_url or "")
        loopback = parsed.hostname in {"localhost", "127.0.0.1", "::1"}
        if not parsed.netloc or parsed.username or parsed.password or parsed.query or parsed.fragment or parsed.path not in {"", "/"}:
            raise ValueError("APP_PUBLIC_URL must be the public origin, for example https://tracker.example.com")
        if parsed.scheme != "https" and not (parsed.scheme == "http" and loopback):
            raise ValueError("Hosted access requires HTTPS; HTTP is only supported for loopback development")
        if parsed.scheme == "http" and self.app_host not in {"localhost", "127.0.0.1", "::1"}:
            raise ValueError("Loopback HTTP development must also bind to loopback")
        self.app_public_url = f"{parsed.scheme}://{parsed.netloc.lower()}"
        if self.app_password_hash_file:
            if self.app_password_hash:
                raise ValueError("Configure only one password hash source")
            try:
                self.app_password_hash = SecretStr(self.app_password_hash_file.read_text(encoding="utf-8").strip())
            except OSError as exc:
                raise ValueError("The configured password hash file cannot be read") from exc
        from app.human_auth import validate_password_hash
        if not self.app_password_hash or not validate_password_hash(self.app_password_hash.get_secret_value()):
            raise ValueError("Hosted access requires a valid password hash generated by application-tracker-password")
        return self

    @field_validator("log_level", mode="before")
    @classmethod
    def normalize_log_level(cls, value: str) -> str:
        return value.lower()

    @field_validator("app_data_dir", mode="after")
    @classmethod
    def resolve_data_dir(cls, value: Path) -> Path:
        value = value.expanduser()
        return (PROJECT_ROOT / value).resolve() if not value.is_absolute() else value.resolve()

    @field_validator("app_static_dir", mode="after")
    @classmethod
    def resolve_static_dir(cls, value: Path) -> Path:
        value = value.expanduser()
        return (PROJECT_ROOT / value).resolve() if not value.is_absolute() else value.resolve()
