"""Generate a persistent VAPID key; never print private key material."""
import argparse
import base64
from pathlib import Path
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec
from pydantic import EmailStr, TypeAdapter


def read_key(path: Path):
    try:
        key = serialization.load_pem_private_key(path.read_bytes(), password=None)
        if not isinstance(key, ec.EllipticCurvePrivateKey) or not isinstance(key.curve, ec.SECP256R1):
            raise ValueError()
        return key
    except (OSError, ValueError, TypeError) as exc:
        raise ValueError("Web Push requires a readable P-256 private key generated by application-tracker-push-key") from exc


def public_key(path: Path) -> str:
    raw = read_key(path).public_key().public_bytes(serialization.Encoding.X962, serialization.PublicFormat.UncompressedPoint)
    return base64.urlsafe_b64encode(raw).decode().rstrip("=")


def validate_contact(value: str):
    if not value.startswith("mailto:"):
        raise ValueError("APP_PUSH_CONTACT must be mailto: followed by an administrator email address")
    TypeAdapter(EmailStr).validate_python(value[7:])


def run():
    parser = argparse.ArgumentParser(description="Generate a persistent Web Push VAPID secret")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    try:
        key = ec.generate_private_key(ec.SECP256R1())
        args.output.parent.mkdir(parents=True, exist_ok=True)
        with args.output.open("xb") as handle:
            args.output.chmod(0o600)
            handle.write(key.private_bytes(serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8, serialization.NoEncryption()))
    except OSError as exc:
        parser.error(str(exc))
    print(f"VAPID key saved to {args.output}. Keep it private and stable across deployments.")


if __name__ == "__main__":
    run()
